import Home from "./Home";
import NotFound from "./NotFound";
import CarItemDetails from "./CarItemDetails";
import Booking from "./Booking";
import Register from "./Register";
import Login from "./Login";
import AccessDenied from "./AccessDenied";
import AuthenticationTest from "./AuthenticationTest";
import AuthenticationTestAdmin from "./AuthenticationTestAdmin";
import Payment from "./Payment";
import OrderConfirmed from "./Order/OrderConfirmed";
export {Register,Login,Home,NotFound,CarItemDetails,Booking,AccessDenied,AuthenticationTest,AuthenticationTestAdmin,Payment,OrderConfirmed};